// <auto-generated />
using System;
using KeyboardBindings.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KeyboardBindings.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260830222904_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("KeyboardBindings.Api.Data.KeyMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyboardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte>("MappedCode")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("PhysicalCode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KeyboardName", "PhysicalCode")
                        .IsUnique();

                    b.ToTable("KeyMappings", t =>
                        {
                            t.HasCheckConstraint("CK_KeyMappings_KeyboardName_MaxLength", "length(\"KeyboardName\") <= 100");
                        });

                    b.HasData(
                        new
                        {
                            Id = 5,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)4,
                            PhysicalCode = (byte)4,
                            Version = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = 6,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)5,
                            PhysicalCode = (byte)5,
                            Version = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = 7,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)6,
                            PhysicalCode = (byte)6,
                            Version = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = 8,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)7,
                            PhysicalCode = (byte)7,
                            Version = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = 9,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)8,
                            PhysicalCode = (byte)8,
                            Version = new Guid("00000000-0000-0000-0000-000000000008")
                        },
                        new
                        {
                            Id = 10,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)9,
                            PhysicalCode = (byte)9,
                            Version = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = 11,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)10,
                            PhysicalCode = (byte)10,
                            Version = new Guid("00000000-0000-0000-0000-00000000000a")
                        },
                        new
                        {
                            Id = 12,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)11,
                            PhysicalCode = (byte)11,
                            Version = new Guid("00000000-0000-0000-0000-00000000000b")
                        },
                        new
                        {
                            Id = 13,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)12,
                            PhysicalCode = (byte)12,
                            Version = new Guid("00000000-0000-0000-0000-00000000000c")
                        },
                        new
                        {
                            Id = 14,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)13,
                            PhysicalCode = (byte)13,
                            Version = new Guid("00000000-0000-0000-0000-00000000000d")
                        },
                        new
                        {
                            Id = 15,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)14,
                            PhysicalCode = (byte)14,
                            Version = new Guid("00000000-0000-0000-0000-00000000000e")
                        },
                        new
                        {
                            Id = 16,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)15,
                            PhysicalCode = (byte)15,
                            Version = new Guid("00000000-0000-0000-0000-00000000000f")
                        },
                        new
                        {
                            Id = 17,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)16,
                            PhysicalCode = (byte)16,
                            Version = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = 18,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)17,
                            PhysicalCode = (byte)17,
                            Version = new Guid("00000000-0000-0000-0000-000000000011")
                        },
                        new
                        {
                            Id = 19,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)18,
                            PhysicalCode = (byte)18,
                            Version = new Guid("00000000-0000-0000-0000-000000000012")
                        },
                        new
                        {
                            Id = 20,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)19,
                            PhysicalCode = (byte)19,
                            Version = new Guid("00000000-0000-0000-0000-000000000013")
                        },
                        new
                        {
                            Id = 21,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)20,
                            PhysicalCode = (byte)20,
                            Version = new Guid("00000000-0000-0000-0000-000000000014")
                        },
                        new
                        {
                            Id = 22,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)21,
                            PhysicalCode = (byte)21,
                            Version = new Guid("00000000-0000-0000-0000-000000000015")
                        },
                        new
                        {
                            Id = 23,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)22,
                            PhysicalCode = (byte)22,
                            Version = new Guid("00000000-0000-0000-0000-000000000016")
                        },
                        new
                        {
                            Id = 24,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)23,
                            PhysicalCode = (byte)23,
                            Version = new Guid("00000000-0000-0000-0000-000000000017")
                        },
                        new
                        {
                            Id = 25,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)24,
                            PhysicalCode = (byte)24,
                            Version = new Guid("00000000-0000-0000-0000-000000000018")
                        },
                        new
                        {
                            Id = 26,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)25,
                            PhysicalCode = (byte)25,
                            Version = new Guid("00000000-0000-0000-0000-000000000019")
                        },
                        new
                        {
                            Id = 27,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)26,
                            PhysicalCode = (byte)26,
                            Version = new Guid("00000000-0000-0000-0000-00000000001a")
                        },
                        new
                        {
                            Id = 28,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)27,
                            PhysicalCode = (byte)27,
                            Version = new Guid("00000000-0000-0000-0000-00000000001b")
                        },
                        new
                        {
                            Id = 29,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)28,
                            PhysicalCode = (byte)28,
                            Version = new Guid("00000000-0000-0000-0000-00000000001c")
                        },
                        new
                        {
                            Id = 30,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)29,
                            PhysicalCode = (byte)29,
                            Version = new Guid("00000000-0000-0000-0000-00000000001d")
                        },
                        new
                        {
                            Id = 31,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)30,
                            PhysicalCode = (byte)30,
                            Version = new Guid("00000000-0000-0000-0000-00000000001e")
                        },
                        new
                        {
                            Id = 32,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)31,
                            PhysicalCode = (byte)31,
                            Version = new Guid("00000000-0000-0000-0000-00000000001f")
                        },
                        new
                        {
                            Id = 33,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)32,
                            PhysicalCode = (byte)32,
                            Version = new Guid("00000000-0000-0000-0000-000000000020")
                        },
                        new
                        {
                            Id = 34,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)33,
                            PhysicalCode = (byte)33,
                            Version = new Guid("00000000-0000-0000-0000-000000000021")
                        },
                        new
                        {
                            Id = 35,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)34,
                            PhysicalCode = (byte)34,
                            Version = new Guid("00000000-0000-0000-0000-000000000022")
                        },
                        new
                        {
                            Id = 36,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)35,
                            PhysicalCode = (byte)35,
                            Version = new Guid("00000000-0000-0000-0000-000000000023")
                        },
                        new
                        {
                            Id = 37,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)36,
                            PhysicalCode = (byte)36,
                            Version = new Guid("00000000-0000-0000-0000-000000000024")
                        },
                        new
                        {
                            Id = 38,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)37,
                            PhysicalCode = (byte)37,
                            Version = new Guid("00000000-0000-0000-0000-000000000025")
                        },
                        new
                        {
                            Id = 39,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)38,
                            PhysicalCode = (byte)38,
                            Version = new Guid("00000000-0000-0000-0000-000000000026")
                        },
                        new
                        {
                            Id = 40,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)39,
                            PhysicalCode = (byte)39,
                            Version = new Guid("00000000-0000-0000-0000-000000000027")
                        },
                        new
                        {
                            Id = 41,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)40,
                            PhysicalCode = (byte)40,
                            Version = new Guid("00000000-0000-0000-0000-000000000028")
                        },
                        new
                        {
                            Id = 42,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)41,
                            PhysicalCode = (byte)41,
                            Version = new Guid("00000000-0000-0000-0000-000000000029")
                        },
                        new
                        {
                            Id = 43,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)42,
                            PhysicalCode = (byte)42,
                            Version = new Guid("00000000-0000-0000-0000-00000000002a")
                        },
                        new
                        {
                            Id = 44,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)43,
                            PhysicalCode = (byte)43,
                            Version = new Guid("00000000-0000-0000-0000-00000000002b")
                        },
                        new
                        {
                            Id = 45,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)44,
                            PhysicalCode = (byte)44,
                            Version = new Guid("00000000-0000-0000-0000-00000000002c")
                        },
                        new
                        {
                            Id = 58,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)57,
                            PhysicalCode = (byte)57,
                            Version = new Guid("00000000-0000-0000-0000-000000000039")
                        },
                        new
                        {
                            Id = 59,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)58,
                            PhysicalCode = (byte)58,
                            Version = new Guid("00000000-0000-0000-0000-00000000003a")
                        },
                        new
                        {
                            Id = 60,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)59,
                            PhysicalCode = (byte)59,
                            Version = new Guid("00000000-0000-0000-0000-00000000003b")
                        },
                        new
                        {
                            Id = 61,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)60,
                            PhysicalCode = (byte)60,
                            Version = new Guid("00000000-0000-0000-0000-00000000003c")
                        },
                        new
                        {
                            Id = 62,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)61,
                            PhysicalCode = (byte)61,
                            Version = new Guid("00000000-0000-0000-0000-00000000003d")
                        },
                        new
                        {
                            Id = 63,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)62,
                            PhysicalCode = (byte)62,
                            Version = new Guid("00000000-0000-0000-0000-00000000003e")
                        },
                        new
                        {
                            Id = 64,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)63,
                            PhysicalCode = (byte)63,
                            Version = new Guid("00000000-0000-0000-0000-00000000003f")
                        },
                        new
                        {
                            Id = 65,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)64,
                            PhysicalCode = (byte)64,
                            Version = new Guid("00000000-0000-0000-0000-000000000040")
                        },
                        new
                        {
                            Id = 66,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)65,
                            PhysicalCode = (byte)65,
                            Version = new Guid("00000000-0000-0000-0000-000000000041")
                        },
                        new
                        {
                            Id = 67,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)66,
                            PhysicalCode = (byte)66,
                            Version = new Guid("00000000-0000-0000-0000-000000000042")
                        },
                        new
                        {
                            Id = 68,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)67,
                            PhysicalCode = (byte)67,
                            Version = new Guid("00000000-0000-0000-0000-000000000043")
                        },
                        new
                        {
                            Id = 69,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)68,
                            PhysicalCode = (byte)68,
                            Version = new Guid("00000000-0000-0000-0000-000000000044")
                        },
                        new
                        {
                            Id = 70,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)69,
                            PhysicalCode = (byte)69,
                            Version = new Guid("00000000-0000-0000-0000-000000000045")
                        },
                        new
                        {
                            Id = 71,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)70,
                            PhysicalCode = (byte)70,
                            Version = new Guid("00000000-0000-0000-0000-000000000046")
                        },
                        new
                        {
                            Id = 72,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)71,
                            PhysicalCode = (byte)71,
                            Version = new Guid("00000000-0000-0000-0000-000000000047")
                        },
                        new
                        {
                            Id = 73,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)72,
                            PhysicalCode = (byte)72,
                            Version = new Guid("00000000-0000-0000-0000-000000000048")
                        },
                        new
                        {
                            Id = 74,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)73,
                            PhysicalCode = (byte)73,
                            Version = new Guid("00000000-0000-0000-0000-000000000049")
                        },
                        new
                        {
                            Id = 75,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)74,
                            PhysicalCode = (byte)74,
                            Version = new Guid("00000000-0000-0000-0000-00000000004a")
                        },
                        new
                        {
                            Id = 76,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)75,
                            PhysicalCode = (byte)75,
                            Version = new Guid("00000000-0000-0000-0000-00000000004b")
                        },
                        new
                        {
                            Id = 77,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)76,
                            PhysicalCode = (byte)76,
                            Version = new Guid("00000000-0000-0000-0000-00000000004c")
                        },
                        new
                        {
                            Id = 78,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)77,
                            PhysicalCode = (byte)77,
                            Version = new Guid("00000000-0000-0000-0000-00000000004d")
                        },
                        new
                        {
                            Id = 79,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)78,
                            PhysicalCode = (byte)78,
                            Version = new Guid("00000000-0000-0000-0000-00000000004e")
                        },
                        new
                        {
                            Id = 80,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)79,
                            PhysicalCode = (byte)79,
                            Version = new Guid("00000000-0000-0000-0000-00000000004f")
                        },
                        new
                        {
                            Id = 81,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)80,
                            PhysicalCode = (byte)80,
                            Version = new Guid("00000000-0000-0000-0000-000000000050")
                        },
                        new
                        {
                            Id = 82,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)81,
                            PhysicalCode = (byte)81,
                            Version = new Guid("00000000-0000-0000-0000-000000000051")
                        },
                        new
                        {
                            Id = 83,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)82,
                            PhysicalCode = (byte)82,
                            Version = new Guid("00000000-0000-0000-0000-000000000052")
                        },
                        new
                        {
                            Id = 84,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)83,
                            PhysicalCode = (byte)83,
                            Version = new Guid("00000000-0000-0000-0000-000000000053")
                        },
                        new
                        {
                            Id = 85,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)84,
                            PhysicalCode = (byte)84,
                            Version = new Guid("00000000-0000-0000-0000-000000000054")
                        },
                        new
                        {
                            Id = 86,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)85,
                            PhysicalCode = (byte)85,
                            Version = new Guid("00000000-0000-0000-0000-000000000055")
                        },
                        new
                        {
                            Id = 87,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)86,
                            PhysicalCode = (byte)86,
                            Version = new Guid("00000000-0000-0000-0000-000000000056")
                        },
                        new
                        {
                            Id = 88,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)87,
                            PhysicalCode = (byte)87,
                            Version = new Guid("00000000-0000-0000-0000-000000000057")
                        },
                        new
                        {
                            Id = 89,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)88,
                            PhysicalCode = (byte)88,
                            Version = new Guid("00000000-0000-0000-0000-000000000058")
                        },
                        new
                        {
                            Id = 90,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)89,
                            PhysicalCode = (byte)89,
                            Version = new Guid("00000000-0000-0000-0000-000000000059")
                        },
                        new
                        {
                            Id = 91,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)90,
                            PhysicalCode = (byte)90,
                            Version = new Guid("00000000-0000-0000-0000-00000000005a")
                        },
                        new
                        {
                            Id = 92,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)91,
                            PhysicalCode = (byte)91,
                            Version = new Guid("00000000-0000-0000-0000-00000000005b")
                        },
                        new
                        {
                            Id = 93,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)92,
                            PhysicalCode = (byte)92,
                            Version = new Guid("00000000-0000-0000-0000-00000000005c")
                        },
                        new
                        {
                            Id = 94,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)93,
                            PhysicalCode = (byte)93,
                            Version = new Guid("00000000-0000-0000-0000-00000000005d")
                        },
                        new
                        {
                            Id = 95,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)94,
                            PhysicalCode = (byte)94,
                            Version = new Guid("00000000-0000-0000-0000-00000000005e")
                        },
                        new
                        {
                            Id = 96,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)95,
                            PhysicalCode = (byte)95,
                            Version = new Guid("00000000-0000-0000-0000-00000000005f")
                        },
                        new
                        {
                            Id = 97,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)96,
                            PhysicalCode = (byte)96,
                            Version = new Guid("00000000-0000-0000-0000-000000000060")
                        },
                        new
                        {
                            Id = 98,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)97,
                            PhysicalCode = (byte)97,
                            Version = new Guid("00000000-0000-0000-0000-000000000061")
                        },
                        new
                        {
                            Id = 99,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)98,
                            PhysicalCode = (byte)98,
                            Version = new Guid("00000000-0000-0000-0000-000000000062")
                        },
                        new
                        {
                            Id = 100,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)99,
                            PhysicalCode = (byte)99,
                            Version = new Guid("00000000-0000-0000-0000-000000000063")
                        },
                        new
                        {
                            Id = 225,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)224,
                            PhysicalCode = (byte)224,
                            Version = new Guid("00000000-0000-0000-0000-0000000000e0")
                        },
                        new
                        {
                            Id = 226,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)225,
                            PhysicalCode = (byte)225,
                            Version = new Guid("00000000-0000-0000-0000-0000000000e1")
                        },
                        new
                        {
                            Id = 227,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)226,
                            PhysicalCode = (byte)226,
                            Version = new Guid("00000000-0000-0000-0000-0000000000e2")
                        },
                        new
                        {
                            Id = 228,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)227,
                            PhysicalCode = (byte)227,
                            Version = new Guid("00000000-0000-0000-0000-0000000000e3")
                        },
                        new
                        {
                            Id = 229,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)228,
                            PhysicalCode = (byte)228,
                            Version = new Guid("00000000-0000-0000-0000-0000000000e4")
                        },
                        new
                        {
                            Id = 230,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)229,
                            PhysicalCode = (byte)229,
                            Version = new Guid("00000000-0000-0000-0000-0000000000e5")
                        },
                        new
                        {
                            Id = 231,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)230,
                            PhysicalCode = (byte)230,
                            Version = new Guid("00000000-0000-0000-0000-0000000000e6")
                        },
                        new
                        {
                            Id = 232,
                            KeyboardName = "Apex Pro Gen 3",
                            MappedCode = (byte)231,
                            PhysicalCode = (byte)231,
                            Version = new Guid("00000000-0000-0000-0000-0000000000e7")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
